version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
jobs:
  bundle_lint_test:
    parameters:
      ruby_type:
        type: string
        default: 'ruby'
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.4.5
      rails_version:
        type: string
      solr_port:
        type: string
        default: '8983'
    docker:
      - image: cimg/<< parameters.ruby_type >>:<< parameters.ruby_version >>-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          RAILS_ENV: test
          RACK_ENV: test
          SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
          RAILS_VERSION: << parameters.rails_version >>
          FCREPO_PORT: 8080
          FCREPO_REST_PATH: fcrepo/rest
          SOLR_TEST_PORT: << parameters.solr_port >>
      - image: fcrepo/fcrepo:6.5-tomcat9
        environment:
          JAVA_OPTS: -Dfcrepo.autoversioning.enabled=false -Dfcrepo.external.content.allowed=/fcrepo_allow.txt
        command: |
          /bin/bash -c "echo 'http://fedoraAdmin:fedoraAdmin@localhost:8080/' > /fcrepo_allow.txt && catalina.sh run"
      - image: solr:7.7-alpine
        command: bin/solr -cloud -noprompt -f -p <<parameters.solr_port>>
    steps:
      - samvera/cached_checkout
      - checkout
      - run:
          name: Check for 'master' branch
          command: |
              git fetch --all --quiet --prune --prune-tags
              if [[ -n "$(git branch --all --list master */master)" ]]; then
                  echo "A branch named 'master' was found. Please remove it."
                  echo "$(git branch --all --list master */master)"
              fi
              [[ -z "$(git branch --all --list master */master)" ]]
              
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/install_solr_core:
          solr_port: <<parameters.solr_port >>

      # Skip rubocop for now
      #- samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby3-3_rails7-2
          ruby_version: 3.3.5
          rails_version: 7.2.1.1
      - bundle_lint_test:
          name: ruby3-3_rails7-1
          ruby_version: 3.3.5
          rails_version: 7.1.4.1
      - bundle_lint_test:
          name: ruby3-3_rails7-0
          ruby_version: 3.3.5
          rails_version: 7.0.8.5
      - bundle_lint_test:
          name: ruby3-2_rails7-2
          ruby_version: 3.2.5
          rails_version: 7.2.1.1
      - bundle_lint_test:
          name: ruby3-2_rails7-1
          ruby_version: 3.2.5
          rails_version: 7.1.4.1
      - bundle_lint_test:
          name: ruby3-2_rails7-0
          ruby_version: 3.2.5
          rails_version: 7.0.8.5
      - bundle_lint_test:
          name: ruby3-1_rails7-2
          ruby_version: 3.1.6
          rails_version: 7.2.1.1
      - bundle_lint_test:
          name: ruby3-1_rails7-1
          ruby_version: 3.1.6
          rails_version: 7.1.4.1
      - bundle_lint_test:
          name: ruby3-1_rails7-0
          ruby_version: 3.1.6
          rails_version: 7.0.8.5
